name = "bark-worker"
main = "main.js"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "database" # available in your Worker on env.database
database_name = "database-bark"
database_id = "<unique-ID-for-your-database>"